# Generated by Django 2.0.4 on 2018-04-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('idade', models.IntegerField()),
                ('data_nasc', models.DateTimeField(verbose_name='%d/%m/%Y')),
            ],
        ),
    ]
