# Generated by Django 2.0.4 on 2018-04-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoDjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_nasc',
            field=models.DateTimeField(verbose_name='Data Nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(verbose_name='Idade'),
        ),
    ]
