# Generated by Django 2.0.4 on 2018-04-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoDjango', '0002_auto_20180412_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_nasc',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Nascimento'),
        ),
    ]
