# Generated by Django 2.0.4 on 2018-04-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoDjango', '0004_auto_20180412_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150, verbose_name='Bairro')),
            ],
        ),
    ]
