# Generated by Django 2.0.4 on 2018-04-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoDjango', '0005_bairro'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalidadeZonaIteravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(choices=[('1', 'Urbana'), ('2', 'Rural')], max_length=1)),
            ],
        ),
    ]
