# Generated by Django 2.0.4 on 2018-04-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoDjango', '0006_localidadezonaiteravel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100, verbose_name='Município')),
                ('uf', models.CharField(choices=[('PR', 'PR'), ('SC', 'SC'), ('RS', 'RS')], max_length=2, verbose_name='UF')),
            ],
        ),
        migrations.DeleteModel(
            name='LocalidadeZonaIteravel',
        ),
    ]
