# Generated by Django 2.0.4 on 2018-04-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoDjango', '0008_modalidadetransporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidadetransporte',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
